### ISSUE TITLE
Health Display Bug

### ISSUE THREAD

**Issue by Necessities3788** [Wutname1/SpartanUI#172]
I have run into a bug where switching between Druid forms causes my health to show the maximum health of of the last form as the current health of the form I'm in. I have attached a screenshot for reference, but here is an example:

I go into my Bear form which currently has max 1,350 HP. Being in travel form causes that to drop to a maximum of 1,080 HP. When I switch to travel form it will show me as having 1,350/1,080. If I switch back into Bear form it will then show 1,080/1,350 and will not regenerate up to 1,350/1,350.

PS: As a minor note I thought I'd throw in there the graphic for War style seems to have an incomplete part on the right side. Arrow pointing at it in the screenshot.

![WoWScrnShot_062619_114807](https://user-images.githubusercontent.com/52228097/60199169-f4755000-9808-11e9-92bd-cbc167c87ccc.jpg)

**Comment by Wutname1** [comment]
I have spent the last 20 minutes shape shifting repeatedly and cant get this to occur for me.

It's been forever since i leveled a druid when you go into bear form do you get a chunk of rage I do on my druid but i am also 120... When you exit bear form if you cast an ability (moonfire something) does your health fix?

**Comment by Necessities3788** [comment]
I do get 25 rage when I switch into bear form. And sadly using abilities does not fix it. I've tried both Moonfire and Regrowth and so far nothing fixes it.

TBH I also get that bug where my LFG "eye" icon shows up away from my minimap.

Could it be something to do with the install? I installed the addon through the Twitch app so maybe its something wrong there.

**Comment by Wutname1** [comment]
The LFG eye bug should be fixed in 5.1.2

**Comment by Necessities3788** [comment]
Ya, I just updated and that's fixed. Still having an issue with the health, though.

**Comment by Wutname1** [comment]
Ah ha found it. It is due to the removal of the percentage. So a quick fix would be to put it back (/sui > Player Frame > Frame Style > Bar Options > Health Text Mode) wow that menu branch is way to long.

**Comment by Necessities3788** [comment]
That did the trick. Thank you very much!
