### ISSUE TITLE
Another Error Lua

### ISSUE THREAD

**Issue by Arwentil** [Wutname1/SpartanUI#38]
Message: Interface\AddOns\SpartanUI\core\WhatsNew.lua:161: unexpected symbol near '+'
Time: Wed Jul 18 23:49:52 2018
Count: 1
Stack: Interface\AddOns\SpartanUI\core\WhatsNew.lua:161: unexpected symbol near '+'

Locals: 

Message: Interface\AddOns\SpartanUI\core\WhatsNew.lua:161: unexpected symbol near '+'
Time: Wed Jul 18 23:51:06 2018
Count: 4

Sorry for bother you but if can help me that would be awesome, thank you so much

**Comment by Wutname1** [comment]
Possibly fixed by 923b11546229c7a9c221a377afe62a14bc4201a6 There is no + in the code so it's likely something other than what the error says is actually causing the error. Let me know if the next update 4.6.3 (will be up tomorrow) fixes it.

**Comment by Wutname1** [comment]
New version up please let me know if the issue persists or changes

**Comment by Arwentil** [comment]
No. Its not fixed but the addon is function well its not like big deal its just every time y put reload or even log in is appear the little box telling me about the error.  But I don't know what its cause the error because the only addon I got is DBM, Skada and SpartanUI + Bartender that's all my addons and all of the are update.

**Comment by Wutname1** [comment]
What language is your client? I cannot reproduce this.
